(import (chicken string)
        (chicken io))
(: read-string-and-split (-> (list-of string)))
(define (read-string-and-split)
    (string-split (read-line) " "))
(: read-width-and-height-from-string-list ((list-of string) -> (list-of number)))
(define (read-width-and-height-from-string-list str-list)
    (assert (= (length str-list) 2))
    (map string->number str-list))
(: read-width-and-height (-> (list-of number)))
(define (read-width-and-height)
    (read-width-and-height-from-string-list (read-string-and-split)))
(print (read-width-and-height))
